# Publishing the Ferengi sacred text "The Rules of Acquisition" at https://ferengi.bible/
#
# $50/year pays for the domain registration.

liberapay: RulesOfAcquisition
ko_fi: rulesofacquisition
buy_me_a_coffee: rulesofacquisition
github: joeyparrish
